// Dev-time codegen: read the schema header from a real reference .bp (READ-ONLY)
// and emit it as a bundled base64 TS asset so the app never touches ../data at runtime.
//
// Usage: node scripts/extractHeader.mjs
import fs from "node:fs";
import path from "node:path";

const REFERENCE =
  "../data/989e5da9-93aa-4f22-bd65-5335d555611a PD Target Distance.bp";

const buf = fs.readFileSync(REFERENCE);
const structCount = buf.readInt32LE(0);
let o = 4;
for (let i = 0; i < structCount; i++) {
  o += 8; // structNameHash (uint64)
  o += 4; // sizeof (int32)
  const fieldCount = buf.readInt32LE(o);
  o += 4;
  o += 16 * fieldCount; // each field: uint64 hash + int32 off + int32 size
}

const header = buf.subarray(0, o);
const b64 = header.toString("base64");

const out =
  "// AUTO-GENERATED by scripts/extractHeader.mjs — do not edit by hand.\n" +
  "// Verbatim schema header extracted from a real v0.1.139 reference blueprint\n" +
  "// (data/989e5da9... PD Target Distance.bp) so the emitted .bp header is byte-exact.\n" +
  `// structCount=${structCount}, headerBytes=${o}.\n` +
  "export const REFERENCE_HEADER_BASE64 =\n" +
  `  "${b64}";\n` +
  `export const REFERENCE_HEADER_BYTE_LENGTH = ${o};\n`;

const dest = path.resolve("src/serializer/referenceHeader.ts");
fs.writeFileSync(dest, out);
console.log(
  `structCount=${structCount} headerBytes=${o} -> wrote ${dest} (b64 len ${b64.length})`,
);
